image:
  file: .Dockerfile
ports:
  - port: 6080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: export JAVA_TOOL_OPTIONS='-Xmx4096m -Dsun.java2d.xrender=false'
  - command: mvn compile && mvn exec:java -Dexec.mainClass="com.kingyu.rlbird.ai.TrainBird" -Dexec.args="-p -t"
