image:
  file: .Dockerfile
ports:
  - port: 6080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: export JAVA_TOOL_OPTIONS="-Xmx4096m -Dsun.java2d.xrender=false"
    command:  echo export JAVA_TOOL_OPTIONS=\"-Xmx4096m -Dsun.java2d.xrender=false\" | tee -a ~/.bashrc &&
      exit
  - command: mvn compile && mvn exec:java -Dexec.mainClass="com.kingyu.rlbird.ai.TrainBird" -Dexec.args="-p -t"
