image:
  file: .Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5090
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo export JAVA_TOOL_OPTIONS=\"-Xmx4096m -Dsun.java2d.xrender=false\" | tee -a ~/.bashrc &&
  - command: export JAVA_TOOL_OPTIONS="-Xmx4096m -Dsun.java2d.xrender=false" && gp open /workspace/RL-FlappyBird/src/main/java/com/kingyu/rlbird/ai/TrainBird.java  && mvn compile && mvn exec:java -Dexec.mainClass="com.kingyu.rlbird.ai.TrainBird" -Dexec.args="-p -t"
